version: "3.8"

services:
  mongo:
    container_name: peerprep-mongo
    image: mongo
    restart: always
    volumes:
      - ./mongodb-data:/data/db
    logging:
      driver: journald
    networks:
      - peerprep-network
    expose:
      - "27017"

  postgres:
    container_name: peerprep-postgres
    image: postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    logging:
      driver: journald
    networks:
      - peerprep-network
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "peerprep"
      POSTGRES_PASSWORD: "password"

  executor:
    image: ghcr.io/peerprep/peerprep-executor-service:latest
    container_name: peerprep-executor-service
    restart: always
    networks:
      - peerprep-network
    logging:
      driver: journald
    expose:
      - "9000"

  innkeeper:
    image: ghcr.io/peerprep/peerprep-innkeeper-service:latest
    container_name: peerprep-innkeeper-service
    restart: always
    networks:
      - peerprep-network
    logging:
      driver: journald
    expose:
      - "4100"

  questions:
    image: ghcr.io/peerprep/peerprep-questions-service:latest
    container_name: peerprep-questions-service
    restart: always
    depends_on:
      - mongo
    networks:
      - peerprep-network
    logging:
      driver: journald
    expose:
      - "4000"
    environment:
      MONGODB_URL: "mongodb://peerprep-mongo:27017/questions"

  users:
    image: ghcr.io/peerprep/peerprep-users-service:latest
    container_name: peerprep-users-service
    restart: always
    depends_on:
      - postgres
    networks:
      - peerprep-network
    logging:
      driver: journald
    expose:
      - "6969"
    volumes:
      - ./firebase-auth:/firebase-auth
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: "/firebase-auth/service-account.json"
      POSTGRES_URL: "postgres://peerprep:password@peerprep-postgres/peerprep"

  frontend:
    image: ghcr.io/peerprep/peerprep-frontend:latest
    container_name: peerprep-frontend
    restart: always
    depends_on:
      - questions
      - innkeeper
      - executor
    networks:
      - peerprep-network
    logging:
      driver: journald
    expose:
      - "3000"

  nginx:
    image: ghcr.io/peerprep/peerprep-nginx:latest
    container_name: peerprep-nginx
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - frontend
    networks:
      - peerprep-network
    logging:
      driver: journald
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot
    container_name: peerprep-certbot
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - peerprep-network
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  peerprep-network:
