name: Build Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  EXECUTOR_IMAGE_NAME: peerprep-executor-service
  QUESTIONS_IMAGE_NAME: peerprep-questions-service
  FRONTEND_IMAGE_NAME: peerprep-frontend
  NGINX_IMAGE_NAME: peerprep-nginx

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      executor: ${{ steps.changes.outputs.executor }}
      questions: ${{ steps.changes.outputs.questions }}
      frontend: ${{ steps.changes.outputs.frontend }}
      nginx: ${{ steps.changes.outputs.nginx }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            executor:
              - 'executor/**/*'
            questions:
              - 'questions/**/*'
            frontend:
              - 'frontend/**/*'
            nginx:
              - 'deployment/**/*'

  build-executor-image:
    needs: changes
    if: ${{ needs.changes.outputs.executor == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out Source
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: peerprep
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployment/Dockerfile-executor
          push: true
          tags: ghcr.io/peerprep/${{ env.EXECUTOR_IMAGE_NAME }}:latest

  build-questions-image:
    needs: changes
    if: ${{ needs.changes.outputs.questions == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out Source
        uses: actions/checkout@v2
      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: peerprep
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployment/Dockerfile-questions
          push: true
          tags: ghcr.io/peerprep/${{ env.QUESTIONS_IMAGE_NAME }}:latest

  build-frontend-image:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out Source
        uses: actions/checkout@v2
      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: peerprep
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployment/Dockerfile-frontend
          push: true
          tags: ghcr.io/peerprep/${{ env.FRONTEND_IMAGE_NAME }}:latest

  build-nginx-image:
    needs: changes
    if: ${{ needs.changes.outputs.nginx == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out Source
        uses: actions/checkout@v2
      - name: Log in to the Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: peerprep
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: deployment/Dockerfile-nginx
          push: true
          tags: ghcr.io/peerprep/${{ env.NGINX_IMAGE_NAME }}:latest
